dist: xenial
language: java
jdk: openjdk8

services:
  - docker

branches:
  only:
    - master

stages:
  - name: Build-Application
  - name: Test
  - name: Build-Docker-Image

jobs:
  include:
    - stage: Compile-Application
      script: 
        - mvn compile

    - stage: Test-Application
      script: 
        - mvn test -B

    - stage: Build-Docker-Image
      script: 
        - docker build -t beerlab-service .

